version: '3.8'

services:
  # Backend service (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langchain-chat-backend
    volumes:
      - ./backend:/app/backend
      - ./backend/notebooks:/app/backend/notebooks
    environment:
      - PYTHONPATH=/app
      - OLLAMA_BASE_URL=http://llm:11434  # For LLM service communication
      - JUPYTER_TOKEN=dev  # Default password for Jupyter
    ports:
      - "8000:8000"
      - "8888:8888"  # Jupyter port
    command: >
      sh -c "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=$$JUPYTER_TOKEN --notebook-dir=/app/backend/notebooks & 
             uvicorn api:app --host 0.0.0.0 --port 8000"
    depends_on:
      - llm
    restart: unless-stopped

  # Frontend service (Vite + React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: langchain-chat-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000  # Update this to your backend URL if different
    depends_on:
      - backend
    restart: unless-stopped

  # LLM service (Ollama)
  llm:
    image: ollama/ollama:latest
    container_name: langchain-chat-llm
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
